//
package view;

import Bancodedados.ConexaoBD;
import ClassesBD.BD;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Caio
 */
public class TelaPrincipalMDI extends javax.swing.JFrame {
    private ListadePessoas list;
    private ListadeP list_produto;
    private Listadepedido pedido;
    private BD banco;
    /**
     * Creates new form TelaPrincipalMDI
     */
    public TelaPrincipalMDI() {
        this.list = new ListadePessoas();
        this.pedido = new Listadepedido();
        this.list_produto = new ListadeP();
       
        BD banco = new BD();
        
        for(Cliente c2 : banco.listarCliente()){
            this.list.setClientes(c2);
        }
        for(Funcionarios c2 : banco.listarFuncionario()){
            this.list.setFuncionarios(c2);
        }
        for(Produto c2 : banco.listarProduto()){
            this.list_produto.adicionarP(c2);
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Menu = new javax.swing.JMenuBar();
        Arquivo = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        Cadastrar = new javax.swing.JMenuItem();
        MostrarClientes = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenu();
        CadastrarProdutos = new javax.swing.JMenuItem();
        MostrarTodos = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Pedidos = new javax.swing.JMenu();
        CadastrarPedidos = new javax.swing.JMenuItem();
        ListarPedidos = new javax.swing.JMenuItem();
        Excluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Prestige Elite Std", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Restaurante  Mizuno");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\tEste software possibilita um controle de pedido ao proprietário de um restaurante.\n\n\tAs imagens são de minha autoria.\n\n\tO software marca qual o funcionário estava atendendo à aquele pedido e o Cliente\n\tque fez o pedido referente ao produto/prato cadastrado no cardápio.\n\n\tIsso garante uma maior segurança ao restaurante a erros e falhas ao anotar um pedido,\n\tpermanecendo assim, registrados na máquina. ");
        jScrollPane1.setViewportView(jTextArea1);

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(557, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Arquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone.jpg"))); // NOI18N
        Arquivo.setText("Arquivo");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Arquivo.add(Sair);

        Menu.add(Arquivo);

        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        Clientes.add(Cadastrar);

        MostrarClientes.setText("Mostrar Todos");
        MostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarClientesActionPerformed(evt);
            }
        });
        Clientes.add(MostrarClientes);

        jMenuItem4.setText("Excluir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Clientes.add(jMenuItem4);

        Menu.add(Clientes);

        jMenu1.setText("Funcionário");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Mostrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Excluir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        Menu.add(jMenu1);

        Produtos.setText("Cardápio");

        CadastrarProdutos.setText("Cadastrar Pratos");
        CadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutosActionPerformed(evt);
            }
        });
        Produtos.add(CadastrarProdutos);

        MostrarTodos.setText("Mostrar todos Pratos");
        MostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodosActionPerformed(evt);
            }
        });
        Produtos.add(MostrarTodos);

        jMenuItem5.setText("Excluir Prato");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Produtos.add(jMenuItem5);

        Menu.add(Produtos);

        Pedidos.setText("Pedidos");

        CadastrarPedidos.setText("Cadastrar");
        CadastrarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarPedidosActionPerformed(evt);
            }
        });
        Pedidos.add(CadastrarPedidos);

        ListarPedidos.setText("Listar Pedidos");
        ListarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPedidosActionPerformed(evt);
            }
        });
        Pedidos.add(ListarPedidos);

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        Pedidos.add(Excluir);

        Menu.add(Pedidos);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        
     
        
    }//GEN-LAST:event_ClientesActionPerformed
//CADASTRAR UM CLIENTE
    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        TelaCadastroCliente telaCadClien = new TelaCadastroCliente();
        jDesktopPane1.add(telaCadClien);
        telaCadClien.setVisible(true);
        
        Cliente cl = new Cliente();
        cl = telaCadClien.retornarCliente();
        this.list.setClientes(cl);
        
        
    }//GEN-LAST:event_CadastrarActionPerformed
//CADASTRAR PRODUTO
    private void CadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutosActionPerformed
        
        
            TelaCadastroProdutos telaP = new TelaCadastroProdutos(list_produto);
            jDesktopPane1.add(telaP);
            telaP.setVisible(true);
            Produto t = new Produto();
            ArrayList<Produto> c = new ArrayList<>();
            c = telaP.retornarP();
            list_produto.setP(c);
            
        
        
        
        
        
        
    }//GEN-LAST:event_CadastrarProdutosActionPerformed
//CADASTRAR PEDIDO
    private void CadastrarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarPedidosActionPerformed
        TelaCadastrarPedidos telaCadPedido = new TelaCadastrarPedidos(list_produto,list);
        jDesktopPane1.add(telaCadPedido);
        telaCadPedido.setVisible(true);
        Pedido c = new Pedido();
        c = telaCadPedido.retornaPedido();
        this.pedido.adicionarPedido(c);
        
        
        
    }//GEN-LAST:event_CadastrarPedidosActionPerformed
//MOSTRAR LISTA DE CLIENTES
    private void MostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarClientesActionPerformed
        
        TelaListaCliente telaClien = new TelaListaCliente(this.list);
        
        jDesktopPane1.add(telaClien);
        
        telaClien.setVisible(true);
    }//GEN-LAST:event_MostrarClientesActionPerformed
//MOSTRAR LISTA DE PRODUTOS
    private void MostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodosActionPerformed
        TelaListaProduto telaClien = new TelaListaProduto(list_produto);
        jDesktopPane1.add(telaClien);
        telaClien.setVisible(true);
        
        
        
    }//GEN-LAST:event_MostrarTodosActionPerformed
//MOSTRAR LISTA DE PEDIDOS
    private void ListarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPedidosActionPerformed
        
        
            TelaListaPedido telaClien = new TelaListaPedido(pedido);
            jDesktopPane1.add(telaClien);
            telaClien.setVisible(true);
            
            for(Pedido pe : this.pedido.getPedido()){
                telaClien.preencher(pe);
            }
   
       
    }//GEN-LAST:event_ListarPedidosActionPerformed
//EXCLUIR UM PEDIDO
    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
       if(this.pedido.getPedido().isEmpty()){
            JOptionPane.showMessageDialog(null,"não há clientes cadastrados!");    
        }
        else{
           TelaExcluirPedido telaPedido = new TelaExcluirPedido(pedido);
            jDesktopPane1.add(telaPedido);
            telaPedido.setVisible(true);
            ArrayList<Pedido> w = new ArrayList<>();
            w = telaPedido.retornaPedido();
            this.pedido.setPedido(w);
            
        }
    }//GEN-LAST:event_ExcluirActionPerformed
//FECHAR O PROGRAMA
    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
       this.dispose();
    }//GEN-LAST:event_SairActionPerformed
//EXCLUIR UM CLIENTE
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        if(this.list.getClientes().isEmpty()){
            JOptionPane.showMessageDialog(null,"não há clientes cadastrados!");    

        }
        else{
        
            TelaExcluirCliente telaCliente = new TelaExcluirCliente(list);
            jDesktopPane1.add(telaCliente);
            telaCliente.setVisible(true);
            ArrayList<Cliente> cl = new ArrayList<>();
            cl = telaCliente.retornarCliente(); 
            this.list.mudarClientes(cl);
            
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed
//CADASTRAR UM FUNCIONARIO
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        TelaCadastroFun telaCadFun = new TelaCadastroFun();
        
        jDesktopPane1.add(telaCadFun);
        Funcionarios f = new Funcionarios("","");
        f = telaCadFun.retornarFuncionario();

        this.list.setFuncionarios(f);
        telaCadFun.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed
//EXCLUIR FUNCIONARIO
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            
        if(this.list.getFuncionarios().isEmpty()){
            JOptionPane.showMessageDialog(null,"não há Funcionarios cadastrados!");    

        }
        else{
        
            TelaExcluirFuncionario telaF = new TelaExcluirFuncionario(list);
            jDesktopPane1.add(telaF);
            telaF.setVisible(true);
            ArrayList<Funcionarios> cl = new ArrayList<>();
            cl = telaF.retornarF();
            this.list.mudarFuncionarios(cl);
            
           
            
        }    
    }//GEN-LAST:event_jMenuItem3ActionPerformed
//MOSTRAR LISTA DE FUNCIONÁRIOS
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaListaFun telaFun = new TelaListaFun();
        for(Funcionarios c : this.list.getFuncionarios()){
            telaFun.preencher(c);
        }
        jDesktopPane1.add(telaFun);
        
        telaFun.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed
//Excluir UM PRODUTO
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if(this.list_produto.getP().isEmpty()){
            JOptionPane.showMessageDialog(null,"Não há pratos cadastrados!");    

        }
        else{
        
            TelaExcluirProduto telaP = new TelaExcluirProduto(list_produto);
            jDesktopPane1.add(telaP);
            telaP.setVisible(true);
            ArrayList<Produto> aux = new ArrayList<>();
            aux = telaP.retornarProduto();
            this.list_produto.setP(aux);
            
           
            
        } 
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalMDI().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Arquivo;
    private javax.swing.JMenuItem Cadastrar;
    private javax.swing.JMenuItem CadastrarPedidos;
    private javax.swing.JMenuItem CadastrarProdutos;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JMenuItem ListarPedidos;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MostrarClientes;
    private javax.swing.JMenuItem MostrarTodos;
    private javax.swing.JMenu Pedidos;
    private javax.swing.JMenu Produtos;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
