/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Caio
 */
public class TelaCadastrarPedidos extends javax.swing.JInternalFrame {
    private ArrayList<Cliente> c;
    private ArrayList<Produto> pr;
    private ArrayList<Funcionarios> funcio;
    
    private Pedido pedid;

    /**
     * Creates new form telaCadastrarPedidos
     */
    public TelaCadastrarPedidos(ListadeP produto,ListadePessoas list) {
        initComponents();
        this.pr = new ArrayList<>();
        this.funcio = new ArrayList<>();
        this.c = new ArrayList<>();
        
        this.pedid = new Pedido();
        
        
        
        
        for(Cliente cli : list.getClientes()){
            this.c.add(cli);
            this.boxCliente.addItem(cli.getNome());
        }
        for(Produto prod : produto.getP()){
            this.pr.add(prod);
            this.boxProduto.addItem(prod.getNome());
        }
         for(Funcionarios f : list.getFuncionarios()){
            this.funcio.add(f);
            this.boxFuncionario.addItem(f.getNome());
        }
    }

    public Pedido retornaPedido(){
       
        return this.pedid;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NomeCliente = new javax.swing.JLabel();
        NomeProduto = new javax.swing.JLabel();
        cadastrarP = new javax.swing.JButton();
        boxCliente = new javax.swing.JComboBox<>();
        boxProduto = new javax.swing.JComboBox<>();
        boxFuncionario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de Pedidos");

        NomeCliente.setText("Nome do cliente:");

        NomeProduto.setText("Nome do Prato:");

        cadastrarP.setText("Cadastrar Pedido");
        cadastrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPActionPerformed(evt);
            }
        });

        boxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        boxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxClienteActionPerformed(evt);
            }
        });

        boxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        boxFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel1.setText("Nome Funcionario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NomeCliente)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxCliente, 0, 198, Short.MAX_VALUE)
                            .addComponent(boxProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeCliente)
                    .addComponent(boxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeProduto)
                    .addComponent(boxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(cadastrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPActionPerformed
        this.dispose();
        for(Cliente t : c){
            if(t.getNome().equals(this.boxCliente.getSelectedItem())){
                pedid.setCliente(t);
                
            }
        }
        for(Produto t : pr){
            if(t.getNome().equals(this.boxProduto.getSelectedItem())){
                pedid.setP(t);
                
            }
        }
        
        for(Funcionarios t : funcio){
            if(t.getNome().equals(this.boxFuncionario.getSelectedItem())){
                pedid.setFunciona(t);
                
            }
        }  
        
        JOptionPane.showMessageDialog(null, "Pedido:"+pedid.getP().getNome()+",\n foi cadastrado com SUCESSO!");
        
    }//GEN-LAST:event_cadastrarPActionPerformed

    private void boxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxClienteActionPerformed
                    // TODO add your handling code here:
    }//GEN-LAST:event_boxClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomeCliente;
    private javax.swing.JLabel NomeProduto;
    private javax.swing.JComboBox<Object> boxCliente;
    private javax.swing.JComboBox<Object> boxFuncionario;
    private javax.swing.JComboBox<Object> boxProduto;
    private javax.swing.JButton cadastrarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
